spring:
    profiles:
        active: default
    h2:
        console: 
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: false
        hibernate:
            ddl-auto: update
        
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/data/h2;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
        username: torrssen
        password: torrssen
# logging:
#     level:
#         root: warn
#         com.tarpha: debug

crypto:
    key: 3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*

daum-movie-tv:
    search-url: https://suggest-bar.daum.net/suggest
    limit: 10
